services:
  worker:
    build: .
    container_name: worker
    restart: always

    volumes:
      - .:/var/www/html

    depends_on:
      - redis

    command: ["php", "/var/www/html/app/Worker/NotifierWorker.php"]

    networks:
      - app_network

  api:
    build: .
    container_name: api
    restart: always

    volumes:
      - .:/var/www/html

    depends_on:
      - mysql
      - redis

    networks:
      - app_network

  redis:
    image: redis
    container_name: redis
    restart: always

    ports:
      - "6379:6379"

    networks:
      - app_network

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3360:3306"

    expose:
      - "3306"

    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - ./database/deploy.sql:/docker-entrypoint-initdb.d/deploy.sql

    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

    networks:
      - app_network

networks:
  app_network:
    driver: bridge