services:
  mysql:
    image: mysql
    ports:
      - "3360:3306"

    expose:
      - "3306"

    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - configure_db:/var/lib/mysql

volumes:
  configure_db: